// Code generated for Temich service

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/ChopX4/raketka/order/internal/model"
)

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

type PaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentClient) EXPECT() *PaymentClient_Expecter {
	return &PaymentClient_Expecter{mock: &_m.Mock}
}

// Pay provides a mock function with given fields: ctx, req
func (_m *PaymentClient) Pay(ctx context.Context, req model.PayOrderRequest) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PayOrderRequest) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PayOrderRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PayOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentClient_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type PaymentClient_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.PayOrderRequest
func (_e *PaymentClient_Expecter) Pay(ctx interface{}, req interface{}) *PaymentClient_Pay_Call {
	return &PaymentClient_Pay_Call{Call: _e.mock.On("Pay", ctx, req)}
}

func (_c *PaymentClient_Pay_Call) Run(run func(ctx context.Context, req model.PayOrderRequest)) *PaymentClient_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PayOrderRequest))
	})
	return _c
}

func (_c *PaymentClient_Pay_Call) Return(_a0 string, _a1 error) *PaymentClient_Pay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentClient_Pay_Call) RunAndReturn(run func(context.Context, model.PayOrderRequest) (string, error)) *PaymentClient_Pay_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentClient creates a new instance of PaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
