// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements CancelOrder operation.
	//
	// Cancels an order.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// CreateOrder implements CreateOrder operation.
	//
	// Create order.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (CreateOrderRes, error)
	// GetOrderById implements GetOrderById operation.
	//
	// Get order by uuid.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderById(ctx context.Context, params GetOrderByIdParams) (GetOrderByIdRes, error)
	// OrderPay implements OrderPay operation.
	//
	// Makes payment for a previously created order.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	OrderPay(ctx context.Context, req *OrderPayReq, params OrderPayParams) (OrderPayRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
